DROP TABLE IF EXISTS SURVEY_QUESTIONS;
CREATE TABLE SURVEY_QUESTIONS (
  QUESTION_ID INT PRIMARY KEY AUTO_INCREMENT,
  QUESTION_TEXT TEXT NOT NULL
);

DROP TABLE IF EXISTS SURVEY_CHOICES;
CREATE TABLE SURVEY_CHOICES (
  CHOICE_ID INT PRIMARY KEY AUTO_INCREMENT,
  QUESTION_ID INT,
  CHOICE_NUMBER INT,
  CHOICE_TEXT TEXT
);